# File : .pep8speaks.yml
 
scanner:
    diff_only: True  # If False, the entire file touched by the Pull Request is scanned for errors. If True, only the diff is scanned.
    linter: flake8  # Other option is pycodestyle
 
flake8:  # Other option is pycodestyle
    max-line-length: 120  # Default is 79 in PEP 8
 
no_blank_comment: True  # If True, no comment is made on PR without any errors.
