"""empty message

Revision ID: 60423d1c5af4
Revises: fb7da4962d13
Create Date: 2019-06-18 16:15:32.466572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60423d1c5af4'
down_revision = 'fb7da4962d13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songmoods', sa.Column('responses_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songmoods', 'responses_count')
    # ### end Alembic commands ###
