"""empty message

Revision ID: c3d17df8f564
Revises: ccaa58ea613c
Create Date: 2019-06-11 16:13:02.567878

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3d17df8f564'
down_revision = 'ccaa58ea613c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songmood')
    op.drop_index('fkIdx_158', table_name='songs_artists')
    op.drop_index('fkIdx_161', table_name='songs_artists')
    op.drop_table('songs_artists')
    op.add_column('artists', sa.Column('artist_id', sa.String(length=200), nullable=False))
    op.alter_column('artists', 'genres',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('artists', 'name',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('artists', 'popularity',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('artists', 'artistid')
    op.add_column('songs', sa.Column('name', sa.String(length=300), nullable=True))
    op.drop_column('songs', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('title', mysql.TEXT(), nullable=False))
    op.drop_column('songs', 'name')
    op.add_column('artists', sa.Column('artistid', mysql.VARCHAR(length=200), nullable=False))
    op.alter_column('artists', 'popularity',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('artists', 'name',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('artists', 'genres',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.drop_column('artists', 'artist_id')
    op.create_table('songs_artists',
    sa.Column('songid', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('artistid', mysql.VARCHAR(length=200), nullable=False),
    sa.ForeignKeyConstraint(['artistid'], ['artists.artistid'], name='FK_161'),
    sa.ForeignKeyConstraint(['songid'], ['songs.songid'], name='FK_158'),
    sa.PrimaryKeyConstraint('songid', 'artistid'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('fkIdx_161', 'songs_artists', ['artistid'], unique=False)
    op.create_index('fkIdx_158', 'songs_artists', ['songid'], unique=False)
    op.create_table('songmood',
    sa.Column('songid', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('happy', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.Column('exited', mysql.DOUBLE(asdecimal=True), nullable=False),
    sa.ForeignKeyConstraint(['songid'], ['songs.songid'], name='songid'),
    sa.PrimaryKeyConstraint('songid', 'happy', 'exited'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
