"""empty message

Revision ID: cd97d4a1d041
Revises: 5829cc457eed
Create Date: 2019-06-17 15:31:38.001136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd97d4a1d041'
down_revision = '5829cc457eed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('acousticness', sa.Float(), nullable=True))
    op.add_column('songs', sa.Column('danceability', sa.Float(), nullable=True))
    op.add_column('songs', sa.Column('duration_ms', sa.Float(), nullable=True))
    op.add_column('songs', sa.Column('energy', sa.Float(), nullable=True))
    op.add_column('songs', sa.Column('instrumentalness', sa.Float(), nullable=True))
    op.add_column('songs', sa.Column('key', sa.Float(), nullable=True))
    op.add_column('songs', sa.Column('liveness', sa.Float(), nullable=True))
    op.add_column('songs', sa.Column('loudness', sa.Float(), nullable=True))
    op.add_column('songs', sa.Column('mode', sa.Float(), nullable=True))
    op.add_column('songs', sa.Column('speechiness', sa.Float(), nullable=True))
    op.add_column('songs', sa.Column('tempo', sa.Float(), nullable=True))
    op.add_column('songs', sa.Column('time_signature', sa.Float(), nullable=True))
    op.add_column('songs', sa.Column('valence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'valence')
    op.drop_column('songs', 'time_signature')
    op.drop_column('songs', 'tempo')
    op.drop_column('songs', 'speechiness')
    op.drop_column('songs', 'mode')
    op.drop_column('songs', 'loudness')
    op.drop_column('songs', 'liveness')
    op.drop_column('songs', 'key')
    op.drop_column('songs', 'instrumentalness')
    op.drop_column('songs', 'energy')
    op.drop_column('songs', 'duration_ms')
    op.drop_column('songs', 'danceability')
    op.drop_column('songs', 'acousticness')
    # ### end Alembic commands ###
