"""empty message

Revision ID: ec762a3d649c
Revises: 
Create Date: 2019-06-05 21:59:06.913617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec762a3d649c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('image_url', sa.String(length=200), nullable=True),
    sa.Column('birthdate', sa.DateTime(timezone=20), nullable=True),
    sa.Column('country', sa.String(length=5), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('refresh_token', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
