"""empty message

Revision ID: fb7da4962d13
Revises: 6424bb3a1b5c
Create Date: 2019-06-18 16:12:53.972708

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb7da4962d13'
down_revision = '6424bb3a1b5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songmoods', 'responses_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songmoods', sa.Column('responses_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
